In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = "/kaggle/input/rsna-2023-abdominal-trauma-detection"

In [3]:
Target_cols = ["bowel_healthy", "bowel_injury", "extravasation_healthy",
                   "extravasation_injury", "kidney_healthy", "kidney_low",
                   "kidney_high", "liver_healthy", "liver_low", "liver_high",
                   "spleen_healthy", "spleen_low", "spleen_high","any_injury"]

In [4]:
file_path = "/kaggle/input/rsna-2023-abdominal-trauma-detection"
train_csv=f"{file_path}/train.csv" 
train=pd.read_csv(train_csv) 
train.head()

,patient_id,bowel_healthy,bowel_injury,extravasation_healthy,extravasation_injury,kidney_healthy,kidney_low,kidney_high,liver_healthy,liver_low,liver_high,spleen_healthy,spleen_low,spleen_high,any_injury
0,10004,1,0,0,1,0,1,0,1,0,0,0,0,1,1
1,10005,1,0,1,0,1,0,0,1,0,0,1,0,0,0
2,10007,1,0,1,0,1,0,0,1,0,0,1,0,0,0
3,10026,1,0,1,0,1,0,0,1,0,0,1,0,0,0
4,10051,1,0,1,0,1,0,0,1,0,0,0,1,0,1

In [5]:
train[Target_cols].describe()

,bowel_healthy,bowel_injury,extravasation_healthy,extravasation_injury,kidney_healthy,kidney_low,kidney_high,liver_healthy,liver_low,liver_high,spleen_healthy,spleen_low,spleen_high,any_injury
count,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000
mean,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.021290,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687
std,0.141172,0.141172,0.243993,0.243993,0.233464,0.187666,0.144373,0.302699,0.274866,0.138994,0.316016,0.243424,0.216431,0.444900
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
train[Target_cols].mean()

bowel_healthy            0.979663
bowel_injury             0.020337
extravasation_healthy    0.936447
extravasation_injury     0.063553
kidney_healthy           0.942167
kidney_low               0.036543
kidney_high              0.021290
liver_healthy            0.897998
liver_low                0.082301
liver_high               0.019701
spleen_healthy           0.887512
spleen_low               0.063235
spleen_high              0.049253
any_injury               0.271687
dtype: float64

In [7]:
# Align with sample submission
sub_df = pd.read_csv(f"{file_path}/sample_submission.csv")

In [8]:
sub_df.head(5)

,patient_id,bowel_healthy,bowel_injury,extravasation_healthy,extravasation_injury,kidney_healthy,kidney_low,kidney_high,liver_healthy,liver_low,liver_high,spleen_healthy,spleen_low,spleen_high
0,48843,0.5,0.5,0.5,0.5,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
1,50046,0.5,0.5,0.5,0.5,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
2,63706,0.5,0.5,0.5,0.5,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333

In [9]:
for col, val in zip(Target_cols, train[Target_cols].mean()):
    sub_df[col] = val

In [10]:
sub_df.head(5)

,patient_id,bowel_healthy,bowel_injury,extravasation_healthy,extravasation_injury,kidney_healthy,kidney_low,kidney_high,liver_healthy,liver_low,liver_high,spleen_healthy,spleen_low,spleen_high,any_injury
0,48843,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.02129,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687
1,50046,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.02129,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687
2,63706,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.02129,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687

In [11]:
# Store submission
sub_df.to_csv("submission.csv",index=False)
sub_df.head(2)

,patient_id,bowel_healthy,bowel_injury,extravasation_healthy,extravasation_injury,kidney_healthy,kidney_low,kidney_high,liver_healthy,liver_low,liver_high,spleen_healthy,spleen_low,spleen_high,any_injury
0,48843,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.02129,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687
1,50046,0.979663,0.020337,0.936447,0.063553,0.942167,0.036543,0.02129,0.897998,0.082301,0.019701,0.887512,0.063235,0.049253,0.271687